In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('housing_data.csv')
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
mean = df.mean()
std = df.std()
df = (df- mean)/std
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,-0.419367,0.284548,-1.286636,-0.272329,-0.144075,0.413263,-0.119895,0.140075,-0.981871,-0.665949,-1.457558,0.440616,-1.074499,0.159528
1,-0.416927,-0.487240,-0.592794,-0.272329,-0.739530,0.194082,0.366803,0.556609,-0.867024,-0.986353,-0.302794,0.440616,-0.491953,-0.101424
2,-0.416929,-0.487240,-0.592794,-0.272329,-0.739530,1.281446,-0.265549,0.556609,-0.867024,-0.986353,-0.302794,0.396035,-1.207532,1.322937
3,-0.416338,-0.487240,-1.305586,-0.272329,-0.834458,1.015298,-0.809088,1.076671,-0.752178,-1.105022,0.112920,0.415751,-1.360171,1.181589
4,-0.412074,-0.487240,-1.305586,-0.272329,-0.834458,1.227362,-0.510674,1.076671,-0.752178,-1.105022,0.112920,0.440616,-1.025487,1.486032

In [4]:
y = df['MEDV'].to_numpy()
x = df.drop(['MEDV'],axis=1)

In [5]:
features = df.copy()

In [6]:
corr = features.corr()
corr

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
CRIM,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
ZN,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
INDUS,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
CHAS,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
NOX,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
RM,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
AGE,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
DIS,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
RAD,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
TAX,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
PTRATIO,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
B,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
LSTAT,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
MEDV,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

In [7]:
corr_vals = corr["MEDV"]
corr_vals = dict(corr_vals)
print(corr_vals)

{'CRIM': -0.3883046085868116, 'ZN': 0.3604453424505431, 'INDUS': -0.48372516002837307, 'CHAS': 0.17526017719029843, 'NOX': -0.42732077237328286, 'RM': 0.6953599470715389, 'AGE': -0.3769545650045961, 'DIS': 0.24992873408590394, 'RAD': -0.3816262306397775, 'TAX': -0.46853593356776685, 'PTRATIO': -0.5077866855375618, 'B': 0.33346081965706653, 'LSTAT': -0.7376627261740145, 'MEDV': 1.0}

In [8]:
corr_vals.items()

dict_items([('CRIM', -0.3883046085868116), ('ZN', 0.3604453424505431), ('INDUS', -0.48372516002837307), ('CHAS', 0.17526017719029843), ('NOX', -0.42732077237328286), ('RM', 0.6953599470715389), ('AGE', -0.3769545650045961), ('DIS', 0.24992873408590394), ('RAD', -0.3816262306397775), ('TAX', -0.46853593356776685), ('PTRATIO', -0.5077866855375618), ('B', 0.33346081965706653), ('LSTAT', -0.7376627261740145), ('MEDV', 1.0)])

In [9]:
for key in corr_vals:
    corr_vals[key] = abs(corr_vals[key])

In [10]:
sorted_dict = sorted(corr_vals.items(),key = lambda x: x[1],reverse=True)

In [11]:
sorted_dict

[('MEDV', 1.0),
 ('LSTAT', 0.7376627261740145),
 ('RM', 0.6953599470715389),
 ('PTRATIO', 0.5077866855375618),
 ('INDUS', 0.48372516002837307),
 ('TAX', 0.46853593356776685),
 ('NOX', 0.42732077237328286),
 ('CRIM', 0.3883046085868116),
 ('RAD', 0.3816262306397775),
 ('AGE', 0.3769545650045961),
 ('ZN', 0.3604453424505431),
 ('B', 0.33346081965706653),
 ('DIS', 0.24992873408590394),
 ('CHAS', 0.17526017719029843)]

In [12]:
# taking top k features
def select_features(k):
    columns = []
    count = 0
    for key in sorted_dict:
        if count == k:
            break
        columns.append(key)
        count += 1

    return columns

In [13]:
select_features(3)

[('MEDV', 1.0), ('LSTAT', 0.7376627261740145), ('RM', 0.6953599470715389)]

In [14]:
def LinearRegressionModel(X,y):
    # adding a column of bias to feature dataset
    ones = np.array([1 for i in range(len(X[:,0]))])
    ones = ones.reshape(len(X[:,0]),1)
    X = np.concatenate((ones,X),axis=1)
    
    # finding theta's using normal equation
    X_T = X.T
    X_TX = X_T.dot(X)
    theta = np.linalg.inv(X_TX).dot(X_T).dot(y)
    
    return theta